c this is <time_getdate.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c
c Copyright 2000 by Thomas Forbriger (IfG Stuttgart)
c
c ----
c libtime is free software; you can redistribute it and/or modify
c it under the terms of the GNU General Public License as published by
c the Free Software Foundation; either version 2 of the License, or
c (at your option) any later version. 
c 
c This program is distributed in the hope that it will be useful,
c but WITHOUT ANY WARRANTY; without even the implied warranty of
c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
c GNU General Public License for more details.
c 
c You should have received a copy of the GNU General Public License
c along with this program; if not, write to the Free Software
c Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
c ----
c
c return month and day index from doy index
c
c REVISIONS and CHANGES
c    05/08/2000   V2.0   Thomas Forbriger
c
c ============================================================================
cS
      subroutine time_getdate(day, month, date)
c
c get day and month index for given doy (day of year) in date
c
c input: 
c   date:   absolute date record
c output:
c   day:    day index within month
c   month:  month index within year
c
c last change: V2.00 (05/08/2000)
c
      integer date(7), day, month
cE
      integer days(12,2), d(7)
      integer sel
      logical time_isleapyear
      data days/31,28,31,30,31,30,31,31,30,31,30,31,
     &          31,29,31,30,31,30,31,31,30,31,30,31/
c 
      call time_copy(date, d)
      call time_norm(d)
      day=d(2)
c check for realtive date
      if (d(1).gt.0) then
        if (time_isleapyear(d(1))) then
          sel=2
        else
          sel=1
        endif
        month=1
    1   if (day.le.days(month,sel)) goto 2
          day=day-days(month,sel)
          month=month+1
          goto 1
    2   continue
      else
        month=0
      endif
      return
      end
c
c ----- END OF <time_getdate.f> -----
