c this is <time_fullyear.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c
c Copyright 2000 by Thomas Forbriger (IfG Stuttgart)
c
c ----
c libtime is free software; you can redistribute it and/or modify
c it under the terms of the GNU General Public License as published by
c the Free Software Foundation; either version 2 of the License, or
c (at your option) any later version. 
c 
c This program is distributed in the hope that it will be useful,
c but WITHOUT ANY WARRANTY; without even the implied warranty of
c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
c GNU General Public License for more details.
c 
c You should have received a copy of the GNU General Public License
c along with this program; if not, write to the Free Software
c Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
c ----
c
c create a full qualified year value from a two-digit abbreviation
c
c REVISIONS and CHANGES
c    05/08/2000  V1.0   Thomas Forbriger
c                V2.0   use language specific warning wrapper
c
c ============================================================================
cS
      subroutine time_fullyear(year)
c
c Makes year to be a full 4 digit year value. This is used to set
c the year to a meanigfull value. Notice that this routine does not
c make sense in combination with relative times.
c
c year < 70         ---> year := year+2000
c 69 < year < 100   ---> year := year+1900
c
c last change: V2.00 (05/08/2000)
c
      integer year
cE
      if (year.lt.70) year=year+2000
      if (year.lt.100) year=year+1900
      if (year.lt.1970) 
     &  call time_util_warning_n('time_fullyear',
     &                           'spurious year value: ',year)
      return
      end
c
c ----- END OF <time_fullyear.f> -----
