c this is <time_add.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c
c Copyright 2000 by Thomas Forbriger (IfG Stuttgart)
c
c ----
c libtime is free software; you can redistribute it and/or modify
c it under the terms of the GNU General Public License as published by
c the Free Software Foundation; either version 2 of the License, or
c (at your option) any later version. 
c 
c This program is distributed in the hope that it will be useful,
c but WITHOUT ANY WARRANTY; without even the implied warranty of
c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
c GNU General Public License for more details.
c 
c You should have received a copy of the GNU General Public License
c along with this program; if not, write to the Free Software
c Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
c ----
c
c add two time records
c
c REVISIONS and CHANGES
c    05/08/2000   V1.0   Thomas Forbriger
c                 V2.0   call language specific warning routine
c
c ============================================================================
cS
      subroutine time_add(date1, date2, date3)
c
c date3=date1+date2
c
c One of both should be a relative time: 
c   relative + absolute -> absolute
c   relative + relative -> relative
c   absolute + absolute -> senseless
c
c NOTICE: This version of time_add disregards leap-seconds!
c
c input:
c   date1:  primary time record
c   date2:  time record to be added
c output:
c   date3:  date1+date2       the sum of the input record
c
c last change: V2.00 (05/08/2000)
c
      integer date1(7), date2(7), date3(7)
cE
      integer i
c
      if((date1(1).ne.0).and.(date2(1).ne.0)) call 
     &  time_util_warning('time_add)',
     &                    'adding two absolute times is senseless')
      call time_norm(date1)
      call time_norm(date2)
      do i=1,7
        date3(i)=date1(i)+date2(i)
      enddo
      call time_norm(date3)
      return
      end
c
c ----- END OF <time_add.f> -----
