c this is <time_div.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c
c Copyright 2000 by Thomas Forbriger (IfG Stuttgart)
c
c ----
c libtime is free software; you can redistribute it and/or modify
c it under the terms of the GNU General Public License as published by
c the Free Software Foundation; either version 2 of the License, or
c (at your option) any later version. 
c 
c This program is distributed in the hope that it will be useful,
c but WITHOUT ANY WARRANTY; without even the implied warranty of
c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
c GNU General Public License for more details.
c 
c You should have received a copy of the GNU General Public License
c along with this program; if not, write to the Free Software
c Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
c ----
c
c divide relative time record by an integer
c
c REVISIONS and CHANGES
c    05/08/2000   V1.0   Thomas Forbriger
c                 V2.0   call language specific fatal error wrapper
c
c ============================================================================
cS
      subroutine time_div(date1, date2, n, rest)
c
c Divide relative time 'date1' by integer 'n' and store result in 'date2'.
c 'rest' gives the none dividable rest in microseconds.
c
c input:
c   date1:  relative time value to be divided
c   n:      divisor
c output:
c   date2:  date1/n           regularized relative time value
c   rest:   date1-(n*date2)   integer number of microseconds
c 
c always: date1 >= (n*date2)
c
c last change: V2.00 (05/08/2000)
c
      integer date1(7), date2(7), n, rest
cE
      integer carry, limit(7), help, i
      data limit/-1,-1,24,60,60,1000,1000/
c
      if (date1(1).ne.0) then
        call time_util_fatal('(time_div)','no absolute time allowed')
      else
        carry=0
        do i=2,7
          help=date1(i)+carry*limit(i)
          date2(i)=int(help/n)
          carry=help-n*date2(i)
        enddo
        rest=carry
        date2(1)=0
        call time_norm(date2)
      endif
      return
      end
c
c ----- END OF <time_div.f> -----
