c this is <time_isleapyear.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c
c Copyright 2000 by Thomas Forbriger (IfG Stuttgart)
c
c ----
c libtime is free software; you can redistribute it and/or modify
c it under the terms of the GNU General Public License as published by
c the Free Software Foundation; either version 2 of the License, or
c (at your option) any later version. 
c 
c This program is distributed in the hope that it will be useful,
c but WITHOUT ANY WARRANTY; without even the implied warranty of
c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
c GNU General Public License for more details.
c 
c You should have received a copy of the GNU General Public License
c along with this program; if not, write to the Free Software
c Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
c ----
c
c check for leap year
c
c REVISIONS and CHANGES
c    05/08/2000   V2.0   Thomas Forbriger
c
c ============================================================================
cS
      logical function time_isleapyear(year)
c
c is true if year is a leap-year (else false ;-))
c
c input:
c   year:   full qualified year value to be checked for being a leap-year
c
c last change: V2.00 (05/08/2000)
c
      integer year
cE
      integer iyear
      logical result
c 
      iyear=year
      call time_fullyear(iyear)
      result=(((mod(iyear,4).eq.0).and.(mod(iyear,100).ne.0)).or.
     &     (mod(iyear,400).eq.0)) 
      time_isleapyear=result
      return
      end
c
c ----- END OF <time_isleapyear.f> -----
