c this is <refract_dim.inc>
c------------------------------------------------------------------------------
c
c 17/03/98 by Thomas Forbriger (IfG Stuttgart)
c
c array dimensions to be used in refract
c
c ----
c refract is free software; you can redistribute it and/or modify
c it under the terms of the GNU General Public License as published by
c the Free Software Foundation; either version 2 of the License, or
c (at your option) any later version. 
c 
c refract is distributed in the hope that it will be useful,
c but WITHOUT ANY WARRANTY; without even the implied warranty of
c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
c GNU General Public License for more details.
c 
c You should have received a copy of the GNU General Public License
c along with this program; if not, write to the Free Software
c Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
c ----
c
c REVISIONS and CHANGES
c    17/03/98   V1.0   Thomas Forbriger
c
c==============================================================================
c
      integer maxtraces, maxsamples, maxfiles
      parameter(maxtraces=2500,maxsamples=15000000, maxfiles=80)
c
c ----- END OF refract_dim.inc -----
