# this is <Makefile.synthetics>
# ----------------------------------------------------------------------------
# 
# Copyright (c) 2015 by Thomas Forbriger (BFO Schiltach) 
# 
# simulate synthetic waveforms
# 
# REVISIONS and CHANGES 
#    12/05/2015   V1.0   Thomas Forbriger
#    07/07/2015   V1.1   provide test data with sparse receiver array
#    26/10/2015   V1.2   use printf instead of echo
# 
# ============================================================================
#
# produce synthetic waveforms
# ---------------------------
#
#  comment on bandwith:
#  standard bandwidth is 200Hz
#  we use a sin**3 pulse with 0.0125 s duration
#
#  see tests below
# test source wavelet
# -------------------
#  a sin**3 wavelet with a duration of 0.0125s has its first spectral gap at
#  200 Hz
SRCDURATION=0.0125
SRCLENGTH=1.
srcpulse.sff:
	siggenx 3 $@ -v -o -ot sff -Te $(SRCDURATION) -T $(SRCLENGTH) \
	  -d 0.0001

srcpulse.ps: srcpulse.sff
	stuplox -d $@/ps -E -ty sff -R 0.98 $<
srcpulsespec.ps: srcpulse.sff
	splot $< 0. $@/ps 1.e-1
#
# ======================================================================
# synthetic seismograms for point source
%.PZ.bin %.PR.bin: %.main %.dmod \
  zforce.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).PZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/mv -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).PR.bin 

# synthetic seismograms for line source
%.LZ.bin %.LR.bin: %.main %.dmod \
  zforce.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin -l $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).LZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/mv -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).LR.bin 

acousticfs.PZ.bin acousticfs.PR.bin: acousticfs.main fullspace.dmod \
  exp0.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).PZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/cp -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).PR.bin 
acousticfs.LZ.bin acousticfs.LR.bin: acousticfs.main fullspace.dmod \
  exp0.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin -l $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).LZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/cp -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).LR.bin 

# -----
#  Model Bietigheim, deep vertical force
biet000601.deepsrc.PZ.bin biet000601.deepsrc.PR.bin: biet000601.deepsrc.main \
  biet000601.dmod \
  zforce15.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).PZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/cp -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).PR.bin 

# synthetic seismograms for line source
biet000601.deepsrc.LZ.bin biet000601.deepsrc.LR.bin: biet000601.deepsrc.main \
  biet000601.dmod \
  zforce15.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin -l $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).LZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/cp -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).LR.bin 

# -----
#  Model Bietigheim, explosive source
biet000601.exp.PZ.bin biet000601.exp.PR.bin: biet000601.exp.main \
  biet000601.dmod \
  exp.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).PZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/cp -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).PR.bin 

# synthetic seismograms for line source
biet000601.exp.LZ.bin biet000601.exp.LR.bin: biet000601.exp.main \
  biet000601.dmod \
  exp.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin -l $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).LZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/cp -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).LR.bin 


# ======================================================================
#
# test case Bietigheim with shallow source and sparse receivers
#
biet.zforce.sparse.PZ.bin biet.zforce.sparse.PR.bin: \
  biet.zforce.sparse.main biet000601.dmod \
  zforce.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).PZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/mv -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).PR.bin 

# synthetic seismograms for line source
biet.zforce.sparse.LZ.bin biet.zforce.sparse.LR.bin: \
  biet.zforce.sparse.main biet000601.dmod \
  zforce.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin -l $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).LZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/mv -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).LR.bin 

# ======================================================================
#
# test case homogeneous full space with single force and sparse receivers
#
fs.zforce0.sparse.PZ.bin fs.zforce0.sparse.PR.bin: \
  fs.zforce0.sparse.main fullspace.dmod \
  zforce0.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).PZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/mv -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).PR.bin 

# synthetic seismograms for line source
fs.zforce0.sparse.LZ.bin fs.zforce0.sparse.LR.bin: \
  fs.zforce0.sparse.main fullspace.dmod \
  zforce0.src lin.rcv
	refmetx -v -4 -c -o $(patsubst %.main,%,$<) -ty bin -l $<
	printf "fac  -1.\nend\n" | tidofi -v -o -cs -type bin -Type bin \
	  $(patsubst %.main,%,$<).LZ.bin $(patsubst %.main,%,$<).TZ 
	/bin/rm -fv $(patsubst %.main,%,$<).TZ
	/bin/mv -fv $(patsubst %.main,%,$<).TR $(patsubst %.main,%,$<).LR.bin 

# ----- END OF Makefile.synthetics ----- 
