c this is <fidase_strings.inc>
c------------------------------------------------------------------------------
c
c 10/07/98 by Thomas Forbriger (IfG Stuttgart)
c
c all string information we have to keep or provide
c
c REVISIONS and CHANGES
c    10/07/98   V1.0   Thomas Forbriger
c
c==============================================================================
c
      character*80 string_version
c
      common /fidase_strings/ string_version
c
c ----- END OF fidase_strings.inc -----
