c this is <gr_dim.inc>
c------------------------------------------------------------------------------
c
c 18/11/97 by Thomas Forbriger (IfG Stuttgart)
c
c all parameter definitions
c
c REVISIONS and CHANGES
c    18/11/97   V1.0   Thomas Forbriger
c
c==============================================================================
c
c mod_mlay:     maximum number of layers
c
      integer mod_mlay
      parameter (mod_mlay=60)
c
c ----- END OF gr_dim.inc -----
