#!/bin/sh
# this is <SeitoshBashrc>
# ----------------------------------------------------------------------------
# 
# Copyright (c) 2010, 2015 by Thomas Forbriger (BFO Schiltach) 
# 
# set environment variable for Seitosh Makefiles
# 
# this file should be placed in the home directory as file
# ~/.SeitoshBashrc
# edit this file to suit your needs
#
# insert the following line into ~/.bashrc
#
#   test -s ~/.SeitoshBashrc && . ~/.SeitoshBashrc || true
# 
# REVISIONS and CHANGES 
#    15/08/2010   V1.0   Thomas Forbriger
#    18/09/2010   V1.1   use only TF_WWWBASEDIR (not WWWBASEDIR)
#                        use only TF_REMCMMNT (not REMCMMNT)
#    13/10/2010   V1.2   add MATLABBINDIR
#    21/01/2011   V1.3   add TF_EDIT
#    03/02/2014   V1.4   discard TF_REMCMMNT
#    20/05/2015   V1.5   adjust for Seitosh
# 
# ============================================================================
#

# default is: grant write permission only to file owner
umask 022

# ----------------------------------------------------------------------------

# If you use the same home directory for different platforms (e.g. NFS mounted
# home), you might like to use specific settings.
#
## PLATFORM=$(uname -m)
## case "$PLATFORM" in
##   x86_64)
##          export LOCBINDIR=$HOME/bin/linux64
## #        add more
##          ;;
##   i686|i586)
##          export LOCBINDIR=$HOME/bin/linux32
## #        add more
## # satisfy netscape script
##          ;;
##   *)     
##          echo "ERROR: unknown operating system"
##          ;;
## esac
# ----------------------------------------------------------------------------
#
# set standard environment variables (see src/README.compile)
# -----------------------------------------------------------

# set standard locations
export LOCBINDIR=$HOME/bin
export LOCLIBDIR=$HOME/lib
export LOCINCLUDEDIR=$HOME/include
export LOCSCRIPTDIR=$HOME/bin/scripts

# additional directory for MATLAB executables (mex-files)
export MATLABBINDIR=$HOME/bin/matlab
# Matlab searches for functions in $MATLABPATH
# see http://de.mathworks.com/help/matlab/ref/userpath.html#zmw57dd0e893915
export MATLABPATH=$MATLABBINDIR:$MATLABPATH

# paths for those cases in which pre-compiled code is provided too
export SERVERBINDIR=$HOME/bin/thof
export SERVERLIBDIR=$HOME/lib/thof
export SERVERINCLUDEDIR=$HOME/include

# location of PGPLOT installation
export PGPLOT_DIR=$HOME/repo/pgplot/linuxgfortran

# standard settings
export TF_LINK_PGPLOT="-lpgplot -lX11 -L/usr/X11/lib -L$PGPLOT_DIR"
export TF_LINK_FORTRAN=-lgfortran
export TF_BROWSER=firefox
export TF_WWWBASEDIR=$HOME/public_html/txt/cxx

# standard compiler
export FC=gfortran
export CC=gcc
export CXX=g++
export CPP=cpp

# standard flags
# these variables are overwritten by most Makefiles
export CPPFLAGS="-I$LOCINCLUDEDIR -I$SERVERINCLUDEDIR"
export LDFLAGS="-L$LOCLIBDIR -L$SERVERLIBDIR"
export FFLAGS="-ff2c -Wall -ffixed-line-length-0 -fno-backslash"

# ----------------------------------------------------------------------------

# execution path and man path
# ---------------------------
# remember base to avoid increasing length of variable content
# this is a kind of include-guard
if test -z "$BASEPATH"
then
  export BASEPATH=$PATH
  export BASEMANPATH=$MANPATH
  export BASELDLIBRARYPATH=$LD_LIBRARY_PATH
else
  PATH=$BASEPATH
  MANPATH=$BASEMANPATH
  LD_LIBRARY_PATH=$BASELDLIBRARYPATH
fi

# set path to executables
PATH=$LOCBINDIR:$PATH
PATH=$SERVERBINDIR:$PATH
PATH=$LOCSCRIPTDIR:$PATH
export PATH

# set path to local dynamic libraries
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LOCLIBDIR:$SERVERLIBDIR
export LD_LIBRARY_PATH

# ============================================================================
# PGPLOT specific settings
# ------------------------
#
# this is where to find grfont.dat and rgb.txt and the libreries
## export PGPLOT_DIR=
#
# this is our default device if you give a blank to the selection
export PGPLOT_DEV=/xwin
#
# this is our default device if you give a filename without a slash
# to the selection
export PGPLOT_TYPE=ps
#
# uncomment the following to set global options for the drawing
# axes an labes to the graph (see PGBOX)
# setenv PGPLOT_ENVOPT BC
#
# uncomment the following to change the foreground color
export PGPLOT_FOREGROUND=black
#
# uncomment the following to change the background color
export PGPLOT_BACKGROUND=white
#
# comment the following to turn buffering off
export PGPLOT_BUFFER=yes
#
# uncomment the following to turn on debugging information
# setenv PGPLOT_DEBUG=yes
#
#
# the following variables refer to the postscript-driver
# ------------------------------------------------------
#
# PGPLOT postscript driver
# sets the dimensions an position of the plot-area in units of 1/1000 inch
export PGPLOT_PS_WIDTH=7480
export PGPLOT_PS_HEIGHT=10120
export PGPLOT_PS_HOFFSET=390
export PGPLOT_PS_VOFFSET=780
#
# identify the user who did the plotting
export PGPLOT_IDENT=yes
#
# uncomment the following to put the BoundingBox-statement in the
# Postscript-header (the bounding box will then be maximal)
# if you leave the statement in the Trailer it will be best fitting
# but is not standard and may cause problems therefor
# setenv PGPLOT_PS_BBOX=MAX
#
# uncomment the following to draw the outline of the bounding box
# on the paper
# setenv PGPLOT_PS_DRAW_BBOX=yes
#
# uncomment the following to include the text written into your
# graphics as a readable comment into yout postscript-file
# setenv PGPLOT_PS_VERBOSE_TEXT=yes
#
# uncomment the following to finish every postscript file with CTRL-D (EOF)
# setenv PGPLOT_PS_EOF=yes
#
# uncomment the following to force the use line-drawn graph markers
# instead of postscript fonts
# setenv PGPLOT_PS_MARKERS=NO

# ============================================================================

# highly recommended aliases
alias rm="rm -i -v"
alias cp="cp -i"
alias mv="mv -i"

# ----- END OF SeitoshBashrc ----- 
