c this is <glq_strings.inc>
c------------------------------------------------------------------------------
cS
c
c 13/01/99 by Thomas Forbriger (IfG Stuttgart)
c
c provide some constant strings
c
c REVISIONS and CHANGES
c    13/01/99   V1.0   Thomas Forbriger
c
c model version identifiers
      character*20 mod_version2
      parameter(mod_version2="ModVersion 2")
c
cE
c ----- END OF glq_strings.inc -----
