Homogeneous full space

             number of layers:         2
          this is a flat model    -1.000     reference frequency (Hz):     0.000

        Zb      alpha       beta        rho     Qalpha      Qbeta         Rb
-----------------------------------------------------------------------------
 0.0000000    1.73200    1.00000   1.800000    100.000    100.000     -1.000
 0.0100000    1.73200    1.00000   1.800000    100.000    100.000     -1.000
halfspace:    1.73200    1.00000   1.800000    100.000    100.000     -1.000

     par   units  description
----------------------------------------------------------------------------
      Zb      km  bottom-of-layer depth
   alpha    km/s  P-wave layer velocity
    beta    km/s  S-wave layer velocity
     rho  g/cm^3  layer density
  Qalpha          quality factor related to alpha
   Qbeta          quality factor related to beta
      Rb      km  radius corresponding to bottom of layer


This file was generated by:
MOCON   V1.3   MOdel CONversion                                       

Minimum allowed relative parameter stepsize: 0.1000

A reference frequency of 0Hz means values are frequency independent.

This was and is still a flat model.
