c this is <grepg_ardim.inc>
c ----------------------------------------------------------------------------
c
c Copyright (c) 2003 by Thomas Forbriger (BFO Schiltach) 
c
c basic array dimensions for grepg
c
c ----
c This program is free software; you can redistribute it and/or modify
c it under the terms of the GNU General Public License as published by
c the Free Software Foundation; either version 2 of the License, or
c (at your option) any later version. 
c 
c This program is distributed in the hope that it will be useful,
c but WITHOUT ANY WARRANTY; without even the implied warranty of
c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
c GNU General Public License for more details.
c 
c You should have received a copy of the GNU General Public License
c along with this program; if not, write to the Free Software
c Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
c ----
c
c REVISIONS and CHANGES
c    05/09/2003   V1.0   Thomas Forbriger
c
c ============================================================================
c

      integer maxslo, maxfreq
      integer dimplotslo, dimplotfreq
c dimensions of arrays
      parameter(maxslo=1000)
      parameter(maxfreq=1000)
c divisions for plot
      parameter(dimplotslo=600)
      parameter(dimplotfreq=400)
c
c ----- END OF grepg_ardim.inc ----- 
