c this is <tt_dim.inc>
c------------------------------------------------------------------------------
cS
c
c 16/09/99 by Thomas Forbriger (IfG Stuttgart)
c
c dimensions for arrays
c
c REVISIONS and CHANGES
c    16/09/99   V1.0   Thomas Forbriger
c
c==============================================================================
c
      integer maxlay
      parameter(maxlay=100)
c
c ----- END OF tt_dim.inc -----
