c this is <fidase_para.inc>
c------------------------------------------------------------------------------
c
c 09/07/98 by Thomas Forbriger (IfG Stuttgart)
c
c some parameter settings (common block)
c
c REVISIONS and CHANGES
c    09/07/98   V1.0   Thomas Forbriger
c
c==============================================================================
c
      character*80 para_version
      integer pg_maindevice
c 
      common/params/para_version, pg_maindevice
c
c ----- END OF fidase_para.inc -----
