#!/bin/bash
# this is <checkcopying>
# ----------------------------------------------------------------------------
# 
# Copyright (c) 2014 by Thomas Forbriger (BFO Schiltach) 
# 
# check copyright information provided in source code files
# 
# REVISIONS and CHANGES 
#    19/01/2014   V1.0   Thomas Forbriger
# 
# ============================================================================
#
grep opyright `find . -type f` | cut -f 2 -d ':' | sort | uniq
# ----- END OF checkcopying ----- 
