# this is <Makefile.filters>
# ----------------------------------------------------------------------------
# 
# Copyright (c) 2011 by Thomas Forbriger (BFO Schiltach) 
# 
# test filter programs
#
# ----
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version. 
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# ----
#
# 
# REVISIONS and CHANGES 
#    24/06/2011   V1.0   Thomas Forbriger
#    27/07/2011   V1.1   test trace modifier apply for tidofi
# 
# ============================================================================
#

# test tidofi against stufi
sig.xxx.sff: ;siggen 6 $@  -Tm 0.2 -Te 1.
sigbox.xxx.sff: ;siggen 13 $@  -Ta .5 -T .2 -f 10. -d 0.012

tid.t.xxx.fil tid.s.xxx.fil: ; printf "DBG  0\ntid  270\nend\n" > $@
lpb.t.xxx.fil lpb.s.xxx.fil: ; printf "DBG  0\nlpb  0.05,5\nend\n" > $@
hpb.t.xxx.fil hpb.s.xxx.fil: ; printf "DBG  0\nhpb  0.05,5\nend\n" > $@
lp2.t.xxx.fil lp2.s.xxx.fil: ; printf "DBG  0\nlp2  0.2,0.707\nend\n" > $@
hp2.t.xxx.fil hp2.s.xxx.fil: ; printf "DBG  0\nhp2  0.2,0.707\nend\n" > $@
bp2.t.xxx.fil bp2.s.xxx.fil: ; printf "DBG  0\nbp2  0.2,0.707\nend\n" > $@
he2.t.xxx.fil he2.s.xxx.fil: ; printf "DBG  0\nhe2  0.2,0.707,1.,0.1\nend\n" > $@
le2.t.xxx.fil le2.s.xxx.fil: ; printf "DBG 0\nle2  0.2,0.707,.01,0.1\nend\n" > $@
he1.t.xxx.fil he1.s.xxx.fil: ; printf "DBG  0\nhe1  0.2,1.,0.1\nend\n" > $@
le1.t.xxx.fil le1.s.xxx.fil: ; printf "DBG 0\nle1  0.2,.01,0.1\nend\n" > $@
lp1.t.xxx.fil lp1.s.xxx.fil: ; printf "DBG  0\nlp1  0.2\nend\n" > $@
hp1.t.xxx.fil hp1.s.xxx.fil: ; printf "DBG  0\nhp1  0.2\nend\n" > $@
fac.t.xxx.fil fac.s.xxx.fil: ; printf "DBG  0\nfac  -10.\nend\n" > $@
add.t.xxx.fil add.s.xxx.fil: ; printf "DBG  0\nadd  -1.e2\nend\n" > $@
add1.t.xxx.fil add1.s.xxx.fil: ; printf "DBG  0\nadd  -1.e-1\nend\n" > $@
add2.t.xxx.fil add2.s.xxx.fil: ; printf "DBG  0\nadd  +1.e-1\nend\n" > $@
rev.t.xxx.fil rev.s.xxx.fil: ; printf "DBG  0\nrev  200\nend\n" > $@
# 0.2/(2*pi)=0.031830989
dif.t.xxx.fil dif.s.xxx.fil: ; printf "DBG  0\ndif  0.031830989\nend\n" > $@
del.t.xxx.fil del.s.xxx.fil: ; printf "DBG  1\ndel  -0.05\nend\n" > $@
int.t.xxx.fil int.s.xxx.fil: ; printf "DBG  0\nint  0.031830989\nend\n" > $@
avg.t.xxx.fil avg.s.xxx.fil: ; printf "DBG  0\navg  30\nend\n" > $@
tre.t.xxx.fil tre.s.xxx.fil: ; printf "DBG  0\ntre  100\nend\n" > $@
han.t.xxx.fil: ; printf "DBG  0\nhan  0\nend\n" > $@
han.s.xxx.fil: ; printf "DBG  0\nsis  1,2000000\nend\n" > $@
first.t.xxx.fil: ; printf "DBG  0\nfirst  0\nend\n" > $@
first.s.xxx.fil: ; printf "DBG  0\navg 1\nend\n" > $@
fbl.t.xxx.fil: ; printf "DBG  0\nfbl 0,00,600\nend\n" > $@
fbl.s.xxx.fil: ; printf "DBG  0\nfbl 200,20,600\nend\n" > $@

%.xxx.rules: Makefile
	( echo "%.$(patsubst %.xxx.rules,%,$@).s.xxx.sff:" \
             " %.xxx.sff $(patsubst %.xxx.rules,%,$@).s.xxx.fil"; \
        printf '\tstufi $$(word 2,$$^) -v -o $$< ' \
                '>$$(patsubst %.sff,%.out,$$@) 2>&1\n'; \
        printf '\t/bin/mv -fv $$<.sfi $$@\n'; \
	  echo "%.$(patsubst %.xxx.rules,%,$@).t.xxx.sff:" \
             " %.xxx.sff $(patsubst %.xxx.rules,%,$@).t.xxx.fil"; \
        printf '\ttidofi -cf $$(word 2,$$^)' \
                '-v -o $$@ $$< ' \
                '| tee $$(patsubst %.sff,%.out,$$@) 2>&1\n'; \
        echo "%.$(patsubst %.xxx.rules,%,$@).t.xxx.fil:" \
             " $(patsubst %.xxx.rules,%,$@).t.xxx.fil" \
             '; /bin/ln -sfv $$< $$@'; \
        echo "%.$(patsubst %.xxx.rules,%,$@).s.xxx.fil:" \
             " $(patsubst %.xxx.rules,%,$@).s.xxx.fil" \
             '; /bin/ln -sfv $$< $$@'; \
        ) > $@

FILTERS=lp2 hp2 lp1 hp1 fac add rev dif int avg tre hpb lpb han bp2 he2 le2 \
  he1 le1 tid first fbl add1 add2 del

include $(addsuffix .xxx.rules,$(FILTERS))

REF=sig.xxx.sff
cmp.%.ps: %.s.xxx.sff %.t.xxx.sff $(REF)
	stuplo -d $@/cps -C -t -s x -i -c fT -l 3,2,1 -h 1.,1.2,1.4,1.2 \
        -Y 0.8 -V -X "Zeit (s)" \
        $(word 1,$^) nc: $(word 2,$^) nc: $(word 3,$^) $^
tidofi.%.report.ps: %.t.xxx.sff
	a2ps -1 -o $@ $(patsubst %.sff,%.out,$<)

control.%.xxx.out: %.s.xxx.sff %.t.xxx.sff %.s.xxx.fil %.t.xxx.fil
	tail -n 999 $(patsubst %.sff,%.out,$^) > $@
control.%.ps: control.%.xxx.out
	cat $< \
	  | a2ps -A virtual -o $@ -1 -r -l 100 \
          --center-title="Control files for $(patsubst control.%,cmp.%,$@)"

%.rw.ps: %.ps; gs -sDEVICE=pswrite -dNOPAUSE -dBATCH -sOutputFile=$@ $< 
filter.%.ps: cmp.%.rw.ps control.%.ps
	a2ps -A virtual -o $@ -1 $^ 

#----------------------------------------------------------------------
# test equivalence of lp2, hp2 and bp2
sig1.xxx.sff:
	siggen 5 $@ -v -o -f1 0.01 -f2 10. -n 50 -T 10. -d 0.001
eq2.ps: sig1.bp2.t.xxx.sff sig1.lp2.t.dif.t.xxx.sff sig1.hp2.t.int.t.xxx.sff \
        sig1.lp2.t.dif.t.add1.t.xxx.sff sig1.hp2.t.int.t.add2.t.xxx.sff
	stuplo -d $@/cps -C -t -s x -i -c fT -l 3,2,1 -h 1.,1.2,1.4,1.2 \
        -Y 0.8 -V -X "Zeit (s)" \
        $(word 5,$^) $(wordlist 1,5,$^)  \
        nc: $(word 4,$^) $(wordlist 1,4,$^) \
        nc: $(word 3,$^) $(wordlist 1,3,$^) \
        nc: $(word 2,$^) $(wordlist 1,2,$^) \
        nc: $(word 1,$^) $(wordlist  1,1,$^)

#----------------------------------------------------------------------
# test case for file modifier "a" in tidofi
sig2.xxx.sff: sig1.xxx.sff sig.xxx.sff
	tidofi -v -o $@ $^
sig3.xxx.sff: sig2.xxx.sff lp2.t.xxx.fil
	tidofi -v -o -cf $(word 2,$^) $@ $< t:1 $< a:2 $< a:1
filter.tidofiapplytest.ps: sig3.xxx.sff
	stuplo -d $@/cps -v -c fT -C \
	  $< t:1 nc: $< t:2,3 nc:  $< t:4,5 $< t:1

#----------------------------------------------------------------------
# test case for geophon together with tidofi
#
# impulse response of a geophone damped with a 47 Ohm shunt resistance
resp.xxx.sff:
	geophone -v -Rd1 47.,0. -o $@
# deconvolution filter for damped geophone
deconv.xxx.fil:
	geophone -v -Rd1 47.,0. -resfile $@
# deconvolution of damped geophone impulse response
resp.deconv.xxx.sff: resp.xxx.sff deconv.xxx.fil
	tidofi -v -o -cf $(word 2,$^) $@ $<

filter.geophone.ps: resp.xxx.sff resp.deconv.xxx.sff
	stuplo -d $@/cps -v -c fTF -s x -i -C -R 0.7 -Y 0.7 \
	  $< t:1 $< $(word 2,$^) t:2 nc: $(word 2,$^) t:2

# ----- END OF Makefile.filters ----- 
