#!/bin/bash
# this is <checkcopyright>
# ----------------------------------------------------------------------------
# 
# Copyright (c) 2014 by Thomas Forbriger (BFO Schiltach) 
# 
# check whether files contain a copyright notice
# 
# REVISIONS and CHANGES 
#    19/01/2014   V1.0   Thomas Forbriger
# 
# ============================================================================
#
grep -c "opyright" \
  $(find . -name \*.c -o -name \*.f -o -name \*.cc -o -name \*.h -o -name \*akefil\* -o -name README) \
  | grep ":0$" | grep -v "svn-base" 
# ----- END OF checkcopyright ----- 
