#!/bin/bash
# this is <checklinkedlibs>
# ----------------------------------------------------------------------------
# 
# Copyright (c) 2014 by Thomas Forbriger (BFO Schiltach) 
# 
# check Makefiles for libraries used for linking
# 
# REVISIONS and CHANGES 
#    19/01/2014   V1.0   Thomas Forbriger
# 
# ============================================================================
#
echo report libraries being used to link against
echo
for mf in $(find . -name Makefile\* -a ! -name \*.bak | sort)
do
  echo ${mf}:
  grep ' -l' ${mf} | tr ' ' '\n' | egrep '^-l|PGP' \
    | sed -e 's/-l//' | egrep -v \' | sort | uniq | tr '\n' ' '
  printf '\n\n'
done
# ----- END OF checklinkedlibs ----- 
