c this is <fidase_dim.inc>
c------------------------------------------------------------------------------
c
c 09/07/98 by Thomas Forbriger (IfG Stuttgart)
c
c array dimoensions set for fidase
c
c REVISIONS and CHANGES
c    09/07/98   V1.0   Thomas Forbriger
c
c==============================================================================
c
      integer maxtraces, maxsamples, maxfiles
      parameter(maxtraces=550,maxsamples=10000000, maxfiles=30)
c
c ----- END OF fidase_dim.inc -----
