c this is <glq_pg.inc>
c------------------------------------------------------------------------------
c
c 08/04/98 by Thomas Forbriger (IfG Stuttgart)
c
c some help arrays for plotting
c
c REVISIONS and CHANGES
c    08/04/98   V1.0   Thomas Forbriger
c
c==============================================================================
c
      real pg_data(glqd_mslo, glqd_mfre)
      common /glq_pghelp/pg_data
c
c ----- END OF glq_pg.inc -----
